const WHITE = "#FFFFFF";
const BLACK = "#000000";
const RED = "#FF0000"
const PINK = "#FFAAAA";
const GREY = "#D3D3D3";
const DARK_RED = "#8B0000";

const DEFAULT_BACKGROUND_COLOR = WHITE;
const DEFAULT_FOREGROUND_COLOR = BLACK;
const DEFAULT_LABEL_COLOR = BLACK;

const CANVAS_BACKGROUND_COLOR = "#FFF0F5";